apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-dbf2
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/happy-path-with-depl-tenant/appstudio/dc-metro-map-dbf2@sha256:455e7dc6097e69d4a542e50f78956e7f1787e8b2b750314d380488581dcb0361
        name: my-nodejs
        resources: {}
status: {}
